// @forge-kit/ground-materials -- Ground Materials primitive package
// Re-exports core (framework-agnostic) + react (framework-coupled) + plugin

// Core exports
export {
  ANALYSIS_ABOVE_SURFACES_M,
  analysisAboveSurfacesZ,
  buildBoundaryPolygon,
  buildGroundMaterialBody,
  type CleanBody,
  CleanBodySchema,
  type CleanResponse,
  CleanResponseSchema,
  type CollectParams,
  type CollectParamsInput,
  CollectParamsSchema,
  type CollectResponse,
  CollectResponseSchema,
  DEFAULT_RENDER_Z,
  type DrawEventState,
  type DrawModes,
  darkenColor,
  detectNonWgs84,
  ensureFeatureUuids,
  type FeatureCollection,
  FeatureCollectionSchema,
  filterPolygonFeatures,
  GROUND_MATERIAL_LIST,
  GROUND_MATERIAL_NAME_LIST,
  GROUND_MATERIAL_ORDER,
  GROUND_MATERIAL_REGISTRY,
  type GroundMaterialNameType,
  type GroundMaterialRegistry,
  type GroundMaterialRegistryElement,
  GroundMaterialRegistryElementSchema,
  GroundMaterialRegistrySchema,
  type GroundMaterialsViewport,
  type GroundMaterialType,
  type GroupStats,
  generateDrawStyles,
  groundMaterialRenderZ,
  type ImportPreviewState,
  type LooseFeatureCollection,
  type LooseMaterialLayers,
  loadMaterialPatterns,
  MATERIAL_RENDER_Z,
  type MetersToLatLngFn,
  type MultiMaterialImport,
  MultiMaterialImportSchema,
  type MultiMaterialProcessResult,
  mapNamesToUuids,
  mapUuidsToNames,
  normalizeSdkAreaLayers,
  type ParseError,
  type ParseResult,
  type ParseSuccess,
  type ProcessResult,
  parseGeoJsonFile,
  processImportedFeatures,
  processMultiMaterialImport,
  RENDER_Z_STEP_M,
  regroupCleanResults,
  rgbToHex,
  SIM_RENDER_HIERARCHY,
  setDrawLayerVisibility,
  sortGroundMaterialsFeatures,
  TOP_SURFACE_RENDER_Z,
} from './core'

// Plugin factory + hook
export {
  createGroundMaterialsPlugin,
  type GroundMaterialsApiClient,
  type GroundMaterialsDeps,
  type GroundMaterialsPluginData,
  useGroundMaterialsMapPlugin,
} from './plugin'

// React exports
export {
  analysisKeys,
  buildAnalysisGroundMaterials,
  buildFallbackWarning,
  createGroundMaterialsAreaLayer,
  DEFAULT_FALLBACK_MATERIAL,
  DrawControl,
  type GroundMaterialsAreaLayerOptions,
  type GroundMaterialsAreaResult,
  type GroundMaterialsAreaStatus,
  type GroundMaterialsPanelDeps,
  type GroundMaterialsSdkClient,
  GroundMaterialsUnavailableError,
  getDrawInstance,
  getGroundMaterialsInitialState,
  getMetersToLatLng,
  groundMaterialsKeys,
  type MaterialLayers,
  type PerFeatureMaterialResolution,
  resolvePerFeatureMaterials,
  setGroundMaterialsApiClient,
  setMetersToLatLng,
  useCleanGroundMaterials,
  useCollectAndProcessGroundMaterials,
  useCollectGroundMaterials,
  useGroundMaterialRegistry,
  useGroundMaterialsAreaMutation,
  useGroundMaterialsDraw,
  useGroundMaterialsStore,
} from './react'
